version: '3.7'
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    image: example-app-image
    container_name: example-app-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - example-app
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html
    networks:
        - example-app
    depends_on:
      - app
  rabbitmq_1:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_1
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - example-app
networks:
    example-app:
        driver: bridge